all:
  children:
    shici:
      hosts:
        www.shi-ci.com:
  # global vars:
  vars:
    app:
      name: shici
      cmd: java -Xms{{ xmx }}m -Xmx{{ xmx }}m -jar /srv/shici/shici.jar
      domain: www.shi-ci.com
      env:
        PROFILES: production
